# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desciption', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('visible', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
