# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 04:09
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_image',
            field=models.ImageField(default='/media/hat.jpg', storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
    ]
