# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 02:37
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(default='hat.jpg', storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message_type',
            field=models.CharField(choices=[('refunds', 'Refund and Cancellation'), ('missing', 'Where is my stuff?'), ('violation', 'Report violation of Terms of Service'), ('phishing', 'Report a phishing incident'), ('general', 'Report general issue')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Closed')], default='open', max_length=6),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('new', 'New Order'), ('shipped', 'Order Shipped'), ('completed', 'Order Completed'), ('cancelled', 'Order Cancelled')], default='new', max_length=20),
        ),
    ]
