# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[(b'new', b'New Order'), (b'shipped', b'Order Shipped'), (b'completed', b'Order Completed'), (b'cancelled', b'Order Cancelled')], default=b'new', max_length=20),
        ),
    ]
