# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0002_auto_20160514_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=30)),
                ('to', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
