# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0002_auto_20160512_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='all', max_length=100),
        ),
    ]
