# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0002_auto_20160522_0237'),
        ('web_shop', '0002_auto_20160522_1658'),
    ]

    operations = [
    ]
