# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0002_auto_20160522_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
