# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_type',
            field=models.CharField(choices=[(b'general', b'Report general issue'), (b'feedback', b'Give us feedback'), (b'refunds', b'Refund and Cancellation'), (b'missing', b'Where is my stuff?'), (b'violation', b'Report violation of Terms of Service'), (b'phishing', b'Report a phishing incident')], default=b'general', max_length=20),
        ),
    ]
