# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0004_auto_20160523_0642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatNotification',
            new_name='Notification',
        ),
    ]
